--- #YAML:1.0
name:                Data-Validate-IP
version:             0.08
abstract:            ip validation methods
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Net::Netmask:                  0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Neil Neely <neil@neely.cx>
