---
abstract: 'ipv4 and ipv6 validation methods'
author:
  - 'Neil Neely <neil@neely.cx>'
  - 'Dave Rolsky <autarch@urth.org>'
build_requires:
  Test::More: 0.88
  Test::Requires: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Validate-IP
requires:
  Exporter: 0
  NetAddr::IP: 4
  Scalar::Util: 0
  perl: 5.008
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Data-Validate-IP
  repository: git://git.urth.org/Data-Validate-IP.git
version: 0.19
x_authority: cpan:NEELY
